server:
  port: 8081

spring:
  application:
    name: file-storing-service

  datasource:
    url: jdbc:postgresql://file-storing-db:5432/file_storing
    driver-class-name: org.postgresql.Driver
    username: app
    password: app

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: student-works

app:
  analysis-service:
    url: http://file-analysis-service:8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always