server:
  port: 8082

spring:
  application:
    name: file-analysis-service

  datasource:
    url: jdbc:postgresql://file-analysis-db:5432/file_analysis
    driver-class-name: org.postgresql.Driver
    username: app
    password: app

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  file-storing-service:
    url: http://file-storing-service:8081
  file:
    max-size: 1048576
    allowed-formats:
      - pdf
      - docx
      - txt

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always